/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizgame;

import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class Quizgame1 extends javax.swing.JFrame {

    /**
     * Creates new form Quizgame1
     */
    public Quizgame1() {
        initComponents();
        setVisible(true);
        setBounds(50,20,1200,700);
       // lbb1.setIcon(new ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuizGame\\src\\quizgame\\image\\hang11.gif"));
         //lbb2.setIcon(new ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuizGame\\src\\quizgame\\image\\hang10.gif"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic17 = new javax.swing.JLabel();
        pic16 = new javax.swing.JLabel();
        pic15 = new javax.swing.JLabel();
        pic14 = new javax.swing.JLabel();
        pic13 = new javax.swing.JLabel();
        pic12 = new javax.swing.JLabel();
        pic11 = new javax.swing.JLabel();
        pic10 = new javax.swing.JLabel();
        pic9 = new javax.swing.JLabel();
        pic8 = new javax.swing.JLabel();
        pic7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pic5 = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        ans1 = new javax.swing.JTextField();
        q2 = new javax.swing.JLabel();
        ans2 = new javax.swing.JTextField();
        q3 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic6 = new javax.swing.JLabel();
        ans3 = new javax.swing.JTextField();
        ans4 = new javax.swing.JTextField();
        q5 = new javax.swing.JLabel();
        ans5 = new javax.swing.JTextField();
        b1 = new javax.swing.JLabel();
        w = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pic17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/cross.png"))); // NOI18N
        pic17.setText(" ");
        getContentPane().add(pic17);
        pic17.setBounds(590, 590, 80, 60);

        pic16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/tic.png"))); // NOI18N
        pic16.setText(" ");
        getContentPane().add(pic16);
        pic16.setBounds(580, 590, 90, 50);

        pic15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/cross.png"))); // NOI18N
        pic15.setText(" ");
        getContentPane().add(pic15);
        pic15.setBounds(420, 500, 80, 60);

        pic14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/tic.png"))); // NOI18N
        pic14.setText(" ");
        getContentPane().add(pic14);
        pic14.setBounds(400, 500, 70, 50);

        pic13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/cross.png"))); // NOI18N
        pic13.setText(" ");
        getContentPane().add(pic13);
        pic13.setBounds(460, 420, 70, 60);

        pic12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/tic.png"))); // NOI18N
        pic12.setText(" ");
        getContentPane().add(pic12);
        pic12.setBounds(450, 410, 70, 60);

        pic11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/cross.png"))); // NOI18N
        pic11.setText(" ");
        getContentPane().add(pic11);
        pic11.setBounds(430, 330, 90, 50);

        pic10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/tic.png"))); // NOI18N
        pic10.setText(" ");
        getContentPane().add(pic10);
        pic10.setBounds(400, 330, 90, 50);

        pic9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/cross.png"))); // NOI18N
        pic9.setText(" ");
        getContentPane().add(pic9);
        pic9.setBounds(430, 260, 60, 40);

        pic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/tic.png"))); // NOI18N
        pic8.setText(" ");
        getContentPane().add(pic8);
        pic8.setBounds(400, 260, 50, 40);

        pic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/winner2-removebg-preview.png"))); // NOI18N
        pic7.setText(" ");
        getContentPane().add(pic7);
        pic7.setBounds(680, 210, 360, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/w1-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1000, 360, 230, 270);

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/dead.png"))); // NOI18N
        pic5.setText(" ");
        getContentPane().add(pic5);
        pic5.setBounds(840, 210, 260, 270);

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/sad1.png"))); // NOI18N
        pic3.setText(" ");
        getContentPane().add(pic3);
        pic3.setBounds(880, 260, 220, 230);

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/hnager.png"))); // NOI18N
        getContentPane().add(pic1);
        pic1.setBounds(630, 150, 450, 420);

        jLabel2.setText(" ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 180, 70, 40);

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/table.png"))); // NOI18N
        pic2.setText(" ");
        pic2.setToolTipText("");
        getContentPane().add(pic2);
        pic2.setBounds(840, 400, 280, 190);

        q1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zz12.png"))); // NOI18N
        q1.setText(" ");
        getContentPane().add(q1);
        q1.setBounds(10, 260, 510, 50);

        ans1.setBackground(new java.awt.Color(255, 153, 255));
        ans1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        ans1.setText(" ");
        ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1ActionPerformed(evt);
            }
        });
        getContentPane().add(ans1);
        ans1.setBounds(40, 310, 240, 30);

        q2.setFont(new java.awt.Font("Yu Gothic Medium", 3, 18)); // NOI18N
        q2.setForeground(new java.awt.Color(51, 0, 0));
        q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zz13.png"))); // NOI18N
        q2.setText(" ");
        getContentPane().add(q2);
        q2.setBounds(0, 340, 410, 50);

        ans2.setBackground(new java.awt.Color(102, 255, 255));
        ans2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        ans2.setText(" ");
        ans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans2ActionPerformed(evt);
            }
        });
        getContentPane().add(ans2);
        ans2.setBounds(50, 390, 240, 30);

        q3.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zz14.png"))); // NOI18N
        q3.setText(" ");
        getContentPane().add(q3);
        q3.setBounds(10, 430, 510, 40);

        q4.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        q4.setForeground(new java.awt.Color(204, 204, 0));
        q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zz16.png"))); // NOI18N
        q4.setText(" ");
        getContentPane().add(q4);
        q4.setBounds(0, 500, 450, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/wlcm-removebg-preview.png"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 390, 350, 240);

        pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/winnwe1-removebg-preview.png"))); // NOI18N
        pic6.setText(" ");
        getContentPane().add(pic6);
        pic6.setBounds(360, 90, 320, 370);

        ans3.setBackground(new java.awt.Color(255, 255, 51));
        ans3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ans3.setText(" ");
        ans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans3ActionPerformed(evt);
            }
        });
        getContentPane().add(ans3);
        ans3.setBounds(50, 480, 240, 30);

        ans4.setBackground(new java.awt.Color(0, 0, 0));
        ans4.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        ans4.setForeground(new java.awt.Color(255, 255, 0));
        ans4.setText(" ");
        ans4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans4ActionPerformed(evt);
            }
        });
        getContentPane().add(ans4);
        ans4.setBounds(40, 560, 240, 30);

        q5.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        q5.setForeground(new java.awt.Color(102, 0, 0));
        q5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zz15.png"))); // NOI18N
        q5.setText(" ");
        q5.setToolTipText("");
        getContentPane().add(q5);
        q5.setBounds(10, 595, 560, 50);

        ans5.setBackground(new java.awt.Color(255, 0, 0));
        ans5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ans5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans5ActionPerformed(evt);
            }
        });
        getContentPane().add(ans5);
        ans5.setBounds(30, 650, 260, 30);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zexit1.png"))); // NOI18N
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b1MouseReleased(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(1140, 20, 50, 50);

        w.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/image/backgroung_hanhman.jpg"))); // NOI18N
        w.setText(" ");
        getContentPane().add(w);
        w.setBounds(-70, -30, 1280, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int w1=0;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pic1.setVisible(false);
       pic2.setVisible(true);
        pic3.setVisible(true);
        // pic4.setVisible(false); 
         pic5.setVisible(false);
           pic6.setVisible(false);
             pic7.setVisible(false);
             pic8.setVisible(false);
             pic9.setVisible(false);
              pic10.setVisible(false);
               pic11.setVisible(false);
               pic12.setVisible(false);
               pic13.setVisible(false);
               pic14.setVisible(false);
               pic15.setVisible(false);
               pic16.setVisible(false);
               pic17.setVisible(false);
               
               
             
        
        q2.setVisible(false);
         q3.setVisible(false);
          q4.setVisible(false);
           q5.setVisible(false);
            
           
           ans2.setVisible(false);
           ans3.setVisible(false);
           ans4.setVisible(false);
           ans5.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1ActionPerformed
        // TODO add your handling code here:
        String A1 = ans1.getText();
        String Rans1 = " 7";
        
        if(A1.equals(Rans1))
        {
            w.setText(""+w1);
            q2.setVisible(true);
            ans2.setVisible(true);
            ans1.setEnabled(false);
             pic8.setVisible(true);
            
        }
        else
        {
            w1=w1+1;
            w.setText(""+w1);
            q2.setVisible(true);
            ans2.setVisible(true);
            ans1.setEnabled(false);
            
            pic1.setVisible(true);
             pic9.setVisible(true);
        }
       
    }//GEN-LAST:event_ans1ActionPerformed

    private void ans4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans4ActionPerformed
        // TODO add your handling code here:
        
          String A1=ans4.getText();
        String Rans4=" east";
        
        int w11 = Integer.parseInt(w.getText());
        
        if(A1.equals(Rans4))
        {
             w.setText(""+w11);
            q5.setVisible(true);
            ans5.setVisible(true);
            ans4.setEnabled(false);
             pic14.setVisible(true);
        }
        else
        {
            w11=w11+1;
            w.setText(""+w11);
             pic15.setVisible(true);
        }
        if(w11==1)
        {
            pic1.setVisible(true);
            q5.setVisible(true);
            ans5.setVisible(true);
            ans4.setEnabled(false);
        }
        //else if(w11==2)
      //  {
       //     pic1.setVisible(true);
        //    q5.setVisible(true);
         //   ans5.setVisible(true);
          //  ans4.setEnabled(false);
       // }
        else if(w11==3)
        {
           // pic1.setVisible(false);
           // pic2.setVisible(false);
            // ans4.setEnabled(false);
             pic5.setVisible(true);
            pic2.setVisible(false);
            pic3.setVisible(false);
            
            ans4.setEnabled(false);
        }
        
    }//GEN-LAST:event_ans4ActionPerformed

    private void ans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans2ActionPerformed
        // TODO add your handling code here:
        String A1=ans2.getText();
        String Rans2=" 365";
        
        int w12 = Integer.parseInt(w.getText());
        
        if(A1.equals(Rans2))
        {
             w.setText(""+w12);
            q3.setVisible(true);
            ans3.setVisible(true);
            ans2.setEnabled(false);
             pic10.setVisible(true);
        }
        else
        {
            w12=w12+1;
            w.setText(""+w12);
             q3.setVisible(true);
            ans3.setVisible(true);
            ans2.setEnabled(false);
             pic11.setVisible(true);
        }
        if(w12==1)
            pic1.setVisible(true);
        else if(w12==2)
        {
           // pic1.setVisible(true);
             pic5.setVisible(true);
            pic2.setVisible(false);
            pic3.setVisible(false);
           ans3.setEnabled(false);
           q3.setEnabled(false);
        }
        
    }//GEN-LAST:event_ans2ActionPerformed

    private void ans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans3ActionPerformed
        // TODO add your handling code here:
        
         String A1=ans3.getText();
        String Rans3=" 7";
        
        int w1 = Integer.parseInt(w.getText());
        
        if(A1.equals(Rans3))
        {
             w.setText(""+w1);
            q4.setVisible(true);
            ans4.setVisible(true);
            ans3.setEnabled(false);
             pic12.setVisible(true);
        }
        else
        {
            w1=w1+1;
            w.setText(""+w1);
             pic13.setVisible(true);
        }
        if(w1==1)
        {
            pic1.setVisible(true);
            q4.setVisible(true);
            ans4.setVisible(true);
            ans3.setEnabled(false);
        }
      //  else if(w1==2)
       // {
         //   pic1.setVisible(true);
         //   q4.setVisible(true);
          //  ans4.setVisible(true);
          //  ans3.setEnabled(false);
       // }
        else if(w1==3)
        {
            //pic1.setVisible(true);
            pic5.setVisible(true);
            pic2.setVisible(false);
            pic3.setVisible(false);
            
            ans3.setEnabled(false);
        }
         
    }//GEN-LAST:event_ans3ActionPerformed

    private void ans5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans5ActionPerformed
        // TODO add your handling code here:
         String A1=ans5.getText();
        String Rans5="26";
         int w12 = Integer.parseInt(w.getText());
        ans4.setEnabled(false);
        ans5.setEnabled(false);
        if(A1.equals(Rans5))
        {
            pic16.setVisible(true);
            pic2.setVisible(false);
            pic1.setVisible(false);
              pic3.setVisible(false);
                pic6.setVisible(true);
                  pic7.setVisible(true);
            
        }
        
         else
        {
            w12=w12+1;
           // w.setText(""+w12);
             pic17.setVisible(true);
        }
        if(w12==1)
        {
            pic1.setVisible(true);
            //q4.setVisible(true);
           // ans4.setVisible(true);
            //ans3.setEnabled(false);
        }
        else if(w12==2)
        {
           // pic1.setVisible(true);
            //q4.setVisible(true);
           // ans4.setVisible(true);
           // ans3.setEnabled(false);
                pic5.setVisible(true);
            pic2.setVisible(false);
            pic3.setVisible(false);
            
            ans5.setEnabled(false);
        }
        //else if(w12==3)
        //{
           // pic1.setVisible(false);
          //  pic2.setVisible(false);
            // ans3.setEnabled(false);
         
       // }
        
    }//GEN-LAST:event_ans5ActionPerformed

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zexit1.png")));
    }//GEN-LAST:event_b1MouseExited

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zexit2.png")));
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseReleased
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_b1MouseReleased
   
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quizgame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quizgame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quizgame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quizgame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Quizgame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans1;
    private javax.swing.JTextField ans2;
    private javax.swing.JTextField ans3;
    private javax.swing.JTextField ans4;
    private javax.swing.JTextField ans5;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic10;
    private javax.swing.JLabel pic11;
    private javax.swing.JLabel pic12;
    private javax.swing.JLabel pic13;
    private javax.swing.JLabel pic14;
    private javax.swing.JLabel pic15;
    private javax.swing.JLabel pic16;
    private javax.swing.JLabel pic17;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic5;
    private javax.swing.JLabel pic6;
    private javax.swing.JLabel pic7;
    private javax.swing.JLabel pic8;
    private javax.swing.JLabel pic9;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel w;
    // End of variables declaration//GEN-END:variables
}
