/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizgame;

/**
 *
 * @author Dell
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        setVisible(true);
        setBounds(420,120,600,520);
        //this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();
        num = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(bar);
        bar.setBounds(10, 460, 500, 20);

        num.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        num.setForeground(new java.awt.Color(0, 0, 204));
        num.setText("99");
        getContentPane().add(num);
        num.setBounds(530, 440, 80, 50);

        txt.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(0, 0, 51));
        txt.setText("Please Wait.......");
        getContentPane().add(txt);
        txt.setBounds(10, 430, 200, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/author.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 460, 230, 80);

        txt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/quiz for kids.png"))); // NOI18N
        txt1.setText(" ");
        getContentPane().add(txt1);
        txt1.setBounds(-10, 170, 620, 386);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/heading.png"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, -110, 420, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizgame/img/zzzww.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //new welcome().setVisible(true);
               // new Quizgame1().setVisible( true);
            }
        });
       // new Quizgame1().setVisible(true);
         welcome Splash = new welcome();
        Splash.setVisible(true);
        
        try
        {
            int i;
            
            
            //audioclass ac1 = new audioclass();
              //  ac1.wait1.play();
            //int i;
            for( i=0; i<=30; i++)
            {
               
                Thread.sleep(80);
               Splash.txt.setText("please wait.............."); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
             
            
            }
           
            Thread.sleep(900);
             //audioclass ac = new audioclass();
            // ac.devlp1.play();
            for( i=30; i<=70; i++)
            {
             
               
                
                
                Thread.sleep(80);
               Splash.txt.setText("Presented BY PRAMOD......"); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
             
            
            }
            
           Thread.sleep(900);
           //audioclass ac3 = new audioclass();
            // ac3.load1.play();
            for( i=70; i<=100; i++)
            {
                              
                Thread.sleep(80);
               Splash.txt.setText("Loading game................."); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
               //Thread.sleep(600);
                  if(i == 100)
            {
                  Thread.sleep(1300);
               Splash.dispose();
                new menu().setVisible(true);
              //  this.setVisible(false);
                   System.out.println("successfully work");
            }
            else
            {
            System.out.println("sorry login again");
            
            }
            }
            // Thread.sleep(1000);
            
        }catch(Exception e){ }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel num;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    // End of variables declaration//GEN-END:variables
}
